apiVersion: v1
kind: Service
metadata:
  name: notice-service
  labels:
    app: notice-service
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: notice-service
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
  labels:
    app: mail-service
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: mail-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-service
  labels:
    version: v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: notice-service
      version: v1
  template:
    metadata:
      labels:
        app: notice-service
        version: v1
    spec:
      containers:
      - name: notice-service
        image: docker.io/vinho0onguyen/my_api:v1
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  labels:
    version: v2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mail-service
      version: v2
  template:
    metadata:
      labels:
        app: mail-service
        version: v2
    spec:
      containers:
      - name: mail-service
        image: docker.io/vinho0onguyen/my_api:v2
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
