apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-destination
spec:
  host: istio-node
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: RANDOM

